### ISSUE TITLE
When trying to connect I'm getting java.lang.NoSuchMethodException: <init> [class com.mbientlab.metawear.impl.DefaultMetaWearBoard, byte, byte], can you guys help? Stacktrace and code sample is below

### ISSUE THREAD

**Issue by petrnalevka** [mbientlab/Metawear-AndroidAPI#5]
Exception:

01-08 11:41:40.401 W/BluetoothGatt( 1650): java.lang.RuntimeException: java.lang.NoSuchMethodException: <init> [class com.mbientlab.metawear.impl.DefaultMetaWearBoard, byte, byte]
01-08 11:41:40.401 W/BluetoothGatt( 1650): 	at com.mbientlab.metawear.impl.DefaultMetaWearBoard.receivedModuleInfo(SourceFile:3225)
01-08 11:41:40.401 W/BluetoothGatt( 1650): 	at com.mbientlab.metawear.MetaWearBleService$2.onCharacteristicChanged(SourceFile:934)
01-08 11:41:40.401 W/BluetoothGatt( 1650): 	at android.bluetooth.BluetoothGatt$1.onNotify(BluetoothGatt.java:438)
01-08 11:41:40.401 W/BluetoothGatt( 1650): 	at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:399)
01-08 11:41:40.401 W/BluetoothGatt( 1650): 	at android.os.Binder.execTransact(Binder.java:453)
01-08 11:41:40.401 W/BluetoothGatt( 1650): Caused by: java.lang.NoSuchMethodException: <init> [class com.mbientlab.metawear.impl.DefaultMetaWearBoard, byte, byte]
01-08 11:41:40.401 W/BluetoothGatt( 1650): 	at java.lang.Class.getConstructor(Class.java:528)
01-08 11:41:40.401 W/BluetoothGatt( 1650): 	at java.lang.Class.getConstructor(Class.java:492)
01-08 11:41:40.401 W/BluetoothGatt( 1650): 	at com.mbientlab.metawear.impl.DefaultMetaWearBoard.receivedModuleInfo(SourceFile:3222)
01-08 11:41:40.401 W/BluetoothGatt( 1650): 	... 4 more

        serviceBinder = (MetaWearBleService.LocalBinder) service;
        mwBoard = serviceBinder.getMetaWearBoard(btDevice);
        mwBoard.setConnectionStateHandler(new MetaWearBoard.ConnectionStateHandler() {
            @Override
            public void connected() {
            }

            @Override
            public void disconnected() {
                mwBoard.connect();
            }

            @Override
            public void failure(int status, Throwable error) {
                Logger.logSevere("MetaWear: connect failed " + status + " ", error);
                mwBoard.connect();
            }
        });

        mwBoard.connect();

**Comment by scaryghost** [comment]
Couple of questions to help debug:
* What MetaWear board are you using?  
* What is the firmware revision?  
* What is your development environment?  
   * jdk, ide, etc.  
* Can you connect to the board with the MetaWear sample app?

**Comment by petrnalevka** [comment]
Many thanks for getting back to me. I tried both sample apps the very
simple one included in the Android API as well as the official Sample app
both built from sources and they both work well.

Tried to compare the code line by line and it seems identical. I tried to
embed your sample activity from the library project directly into my app
and it has the same problem. I use the same targetSdk in my app has the
right dependency to library 2.3.0.. Do you have any ideas or hints what I
could try?

Board: MetaWear R
FW: 1.1.0
IDE: Android Studio

Thank you very much.

Best regards,

Petr

**Comment by petrnalevka** [comment]
Sorry, I think I know the issue, it is probably a proguard problem, sorry
about posting a false alert..

Thank you very much.

Best regards,

Petr

**Comment by petrnalevka** [comment]
Just a suggestion, maybe you want to add some implicit proguard rules to
your sample project. Many thanks for your help on this..

Thank you very much.

Best regards,

Petr

**Comment by biospank** [comment]
Hi Petr,
I'm having the same issue. How did you fixed that?
Please can you help me to figure out what's the problem?

Thanks

**Comment by petrnalevka** [comment]
Sorry, we did abandon the idea to use META Wear for our project so I could
not spend more time on this. But I believe this is somehting which needs to
fixed in the Metawear Android API - I expect a simple null check..

Thank you very much.

Best regards,

Petr

**Comment by scaryghost** [comment]
Do you have any proguard rules?  The library uses some reflection which can be broken from proguard obfuscation.

**Comment by petrnalevka** [comment]
Sorry I though you are referring to the other issue I posted, for this one I used:

-keep class com.mbientlab.** { *; }

**Comment by biospank** [comment]
I had to use:

```
buildTypes {
        release {
            minifyEnabled false
        }
    }
```
to avoid `proguard` remove needed class. Obviously is not the ideal solution.

Can I get the list of files needed to configure `proguard` properly?
