### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.bluetooth.BluetoothGatt.close()' 

### ISSUE THREAD

**Issue by petrnalevka** [mbientlab/Metawear-AndroidAPI#6]
When working with the MetaWearBleService I frequently get the following NPE.

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.bluetooth.BluetoothGatt.close()' on a null object reference
	com.mbientlab.metawear.MetaWearBleService$GattConnectionState$1.run(SourceFile:236)
	android.os.Handler.handleCallback(Handler.java:739)
	android.os.Handler.dispatchMessage(Handler.java:95)
	android.os.Looper.loop(Looper.java:148)
	android.app.ActivityThread.main(ActivityThread.java:5417)
	java.lang.reflect.Method.invoke(Native Method)
	com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by scaryghost** [comment]
I will need more information before I can debug this crash.

* Can this be reliably reproduced?  
   * If so, what are the steps to reproduce this crash?  
* What code is being executed prior to the crash?  

Based on the stack trace, my guess is that your Bluetooth adapter is disabled when you are trying to connect to a board.
